import "reflect-metadata";
import express from "express";
import './database';
import cors from 'cors';
import clientErrorHandle from "./errors/client-error-handler";
const app = express();
app.use(express.json());
app.use(cors());
app.use(clientErrorHandle);
export default app;
